### ISSUE TITLE
模型默认参数设置

### ISSUE THREAD

**Issue by mingchenyue** [CloneNOX/MSA-BiGCN#2]
logName和savePath这两个默认参数不改动的话，提示找不到文件，log目录和model目录要去哪里建立呢

**Comment by CloneNOX** [comment]
MSA-BiGCN/train.py里这两个参数参数默认值为"./log/log.txt"和"./model/model.pt"，意为在工作目录下尝试寻找并进入log和model目录并尝试创建log.txt文件和model.pt文件，如果工作目录下没有这两个目录，会导致代码中诸如`f = open(args.logName, 'w')`的语句执行失败。解决方法：
1. 在执行`python train.py`指令的工作目录下建立log和model目录，例如：在`MSA-BiGCN/MSA-BiGCN/`中建立，然后再该目录下运行train.py。
2. 在执行指令中通过`--logName`和`--savePath`指定已经存在的目录来存储log.txt和model.pt，例如：目录`~/log/`和`~/model/`已经存在，则通过指令`python train.py --logName ~/log/log.txt --savePath ~/model/model.pt [...]`来运行本次训练。

**Comment by mingchenyue** [comment]
谢谢，目录我按照你给的默认路径创建好了，运行train.py文件后输出以下内容，请问训练完输出什么呢，怎么看有没有训练完成呢
ASUS@DESKTOP-UQTSEC7 MINGW64 /d/Program Files (x86)/Git/MSA-BiGCN/MSA-BiGCN (master)
$ python3810 train.py --dataPath ../dataset/semeval2017-task8/ --logName ./log/final/needNoStance/orign/25w2v-64s2v-64hidden-0.2dropout-0.001000weight.txt --savePath ./model/final/needNoStance/orign/25w2v-64s2v-64hidden-0.2dropout-0.001000weight.pt --device cuda:0
preparing data...done.
train ABGCN on device:cuda:0

MSABiGCN(
  (embed): Embedding(6445, 50, padding_idx=0)
  (wordAttention): MultiheadAttention(
    (out_proj): NonDynamicallyQuantizableLinear(in_features=50, out_features=50,
 bias=True)
  )
  (s2vRumor): Linear(in_features=50, out_features=64, bias=True)
  (s2vStance): Linear(in_features=50, out_features=64, bias=True)
  (biGCN): BiGCN(
    (TDGCN): GCN(
      (conv1): GCNConv(128, 256)
      (conv2): GCNConv(384, 256)
    )
    (BUGCN): GCN(
      (conv1): GCNConv(128, 256)
      (conv2): GCNConv(384, 256)
    )
  )
  (f2tRumor): Linear(in_features=1024, out_features=3, bias=True)
  (stanceAttention): MultiheadAttention(
    (out_proj): NonDynamicallyQuantizableLinear(in_features=64, out_features=64,
 bias=True)
  )
  (stanceFc): Linear(in_features=64, out_features=64, bias=True)
  (f2tStance): Linear(in_features=64, out_features=4, bias=True)
)
[epoch: 1] :   0%|                                                          | 0/
272 [00:00<?, ?it/s]fatal   : Memory allocation failure

    (out_proj): NonDynamicallyQuantizableLinear(in_features=50, out_features=50, bias=True)
  )
  (s2vRumor): Linear(in_features=50, out_features=64, bias=True)
  (s2vStance): Linear(in_features=50, out_features=64, bias=True)
  (biGCN): BiGCN(
    (TDGCN): GCN(
      (conv1): GCNConv(128, 256)
      (conv2): GCNConv(384, 256)
    )
    (BUGCN): GCN(
      (conv1): GCNConv(128, 256)
      (conv2): GCNConv(384, 256)
    )
  )
  (f2tRumor): Linear(in_features=1024, out_features=3, bias=True)
  (stanceAttention): MultiheadAttention(
    (out_proj): NonDynamicallyQuantizableLinear(in_features=64, out_features=64, bias=True)
  )
  (stanceFc): Linear(in_features=64, out_features=64, bias=True)
  (f2tStance): Linear(in_features=64, out_features=4, bias=True)
)

**Comment by CloneNOX** [comment]
根据指令参数`--device cuda:0`和你给出的终端显示内容：
```
[epoch: 1] : 0%| | 0/
272 [00:00<?, ?it/s]fatal : Memory allocation failure
```
看起来像是显存申请失败，请检查一下实验的显卡设备显存是否充足。
一般来说：运行`train.py`会默认在stdout输出当前模型的参数信息，运行过程中tqdm模块会输出每个epoch的训练进度，即上面代码块中的部分，同时会在`--logName`参数指定的文件中记录loss，accuracy，F1等性能数据。`train.py`运行结束后，会在log文件中记录训练过程的性能数据，也会在终端打印保存模型的时间点和相关数据（`train.py`的第337行）。

**Comment by mingchenyue** [comment]
可以通过设置batch_size缓解该问题吗，因为确实电脑配置不够......如果可以是在训练参数那里加上parser.add_argument('--batch_size', type=int, default=16,\help='set training batch size, default: 16')就可以了吗

**Comment by mingchenyue** [comment]
可以分享一下论文原文吗，万分感谢

**Comment by CloneNOX** [comment]
当时写这份代码的时候没有留出batch化训练的接口，可以理解为`train.py`的训练默认batch是1。如果这样子还是显存不够的话，可以尝试以下方案：
1. 使用参数`--device cpu`切换到cpu运行，在数据量和SemEval数据集相似的数据上做训练还是可以的，不推荐使用cpu计算和PHEME类似的数据集。
2. 租用带有GPU的服务器。
 
论文通过邮箱发给你。

**Comment by CloneNOX** [comment]
可以的话，点个star吧（doge


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CloneNOX/MSA-BiGCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月27日(星期一) 下午4:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CloneNOX/MSA-BiGCN] 模型默认参数设置 (Issue #2)





 
可以分享一下论文原文吗，万分感谢

**Comment by mingchenyue** [comment]
已点⭐啦，谢谢你的解答和论文，我实在是太小白了，如果可能的话，我想加您个vx可以吗？我们课题组只有我在做这个方向，希望能有机会和您讨论




?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CloneNOX/MSA-BiGCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月27日(星期一) 下午5:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CloneNOX/MSA-BiGCN] 模型默认参数设置 (Issue #2)





 可以的话，点个star吧（doge 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "CloneNOX/MSA-BiGCN"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年2月27日(星期一) 下午4:24 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [CloneNOX/MSA-BiGCN] 模型默认参数设置 (Issue #2) 
 
 
 
 
 
   
 可以分享一下论文原文吗，万分感谢

**Comment by mingchenyue** [comment]
1057239459@qq.com这是我的邮箱

**Comment by syyy721** [comment]
报错无法调用BiGCN模型是为什么呢
